### PR TITLE
[WIP][RFC] new runit PKGBUILDs

### PR DESCRIPTION
**Pull request by konimex**
This PR brings major changes to how Cromnix's runit scripts work.

Basically, `runit` will only provide the binaries (`sv`, `runit-init`, `chpst`, etc.) and the default directories (`/etc/runit`, `/var/service`). All scripts inside `/etc/runit` will be provided by `runit-init`, which I splitted into two packages: `runit-cromnix`, where runit runs standalone, and `runit-cromnix-openrc`, where `runit-init` behaves like `sysvinit` and spawns OpenRC.

For now, `runit-cromnix` is stored in [my github](https://github.com/konimex/runit-cromnix) but I recommend that the repo to be moved into your github instead.

Because `runit` cannot run on its own, it'll either need `runit-cromnix` or `runit-cromnix-openrc`, I'm still not sure how the dependency will be handled.

### CODE REVIEW

**Comment by cromerc** [comment]
This looks very good, I will build and merge this tomorrow after testing it out.

**Comment by konimex** [comment]
I'll need help for the dependency resolution. Currently it's like this:

`runit` depends on `runit-init`, but `runit-init` by itself doesn't exist as a PKGBUILD/group, but it's provided by `runit-cromnix` and `runit-cromnix-openrc`. 

Does that sound good enough? I'm afraid when people install `runit`, pacman will not be able to resolve its dependencies.

**Comment by cromerc** [comment]
I believe those dependencies are fine. Depends are alphabetic, so runit-cromnix should be pulled in by default and the openrc variant would be a secondary option. So I don't think that will cause any issues during install.

I played around with it a little bit and it is working very well. I am going to merge this and am going to import your runit-cromnix repo into the cromnix organizations' repos.

**Comment by cromerc** [comment]
After some cleanup and tiny modifications I have pushed all the new runit packages into the repos.

**Pull request merged**
